// <auto-generated />
using System;
using System.Text.Json;
using Codx.Temple.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Codx.Temple.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803145307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Codx.Temple.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentPublishedVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPublishedVersionId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.LessonNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresPriorSiblingAnswered")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("LessonVersionId");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("LessonNodes");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.LessonVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ClonedFromVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClonedFromVersionId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonVersions");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonNodeId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("ReferenceContext")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("LessonNodeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("RoleAssignments");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Codx.Temple.Domain.Entities.LessonVersion", "CurrentPublishedVersion")
                        .WithMany()
                        .HasForeignKey("CurrentPublishedVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentPublishedVersion");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.LessonNode", b =>
                {
                    b.HasOne("Codx.Temple.Domain.Entities.LessonVersion", "LessonVersion")
                        .WithMany("Nodes")
                        .HasForeignKey("LessonVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Codx.Temple.Domain.Entities.LessonNode", "ParentNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LessonVersion");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.LessonVersion", b =>
                {
                    b.HasOne("Codx.Temple.Domain.Entities.LessonVersion", "ClonedFromVersion")
                        .WithMany()
                        .HasForeignKey("ClonedFromVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Codx.Temple.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Versions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClonedFromVersion");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.Question", b =>
                {
                    b.HasOne("Codx.Temple.Domain.Entities.LessonNode", "LessonNode")
                        .WithMany("Questions")
                        .HasForeignKey("LessonNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonNode");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.RoleAssignment", b =>
                {
                    b.HasOne("Codx.Temple.Domain.Entities.User", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Codx.Temple.Domain.Entities.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assigner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.LessonNode", b =>
                {
                    b.Navigation("ChildNodes");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.LessonVersion", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Codx.Temple.Domain.Entities.User", b =>
                {
                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
